config/routes.rb
Fasttwitter::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "test" => "pages#test" , :as => "test"
  root :to => "users#index"
  resources :users do
    resources :microposts
  end
  resources :sessions

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content
  
  belongs_to :user
  
  validates_presence_of :content, :length => { :maximum => 250 }
  validates_presence_of :user_id
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :password, :email, :password_confirmation
  before_save :encrypt_password
  
  has_many :microposts, :dependent => :destroy
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :email,
            :presence => true,
            :uniqueness => true,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  helper_method :logged_in?
         
private
         
  def logged_in?
    if session[:user_id] == @user.id
      @user
    else
      nil
    end
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
       
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  respond_to :html, :js
  
  def new
    @micropost = Micropost.new
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.html
      format.xml { render json: @micropost }
    end
  end
  
  def create
    @user = User.find(params[:user_id])
    @micropost = @user.microposts.new(params[:micropost])
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to(@user) }
        format.xml { render :xml => @user, :status => :created, :location => @user }
        format.js
      else
        format.html { redirect_to(@user) }
        format.xml { render :xml => @micropost.errors }
        format.js
      end
    end
  end
  
  def edit
    @user = User.find(params[:id])
    if current_user
      if current_user == @user
        current_user
      end
    else
      redirect_to @user, :notice => "You cannot edit another user's post"
    end

    @micropost = @user.microposts.find(params[:user_id])  
  end
  
  def destroy
    @user = User.find(params[:id])
    @micropost = Micropost.find(params[:user_id])
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to(@user) }
      format.js
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  
  def test
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to user_path(user), :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
      format.js
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.find(params[:id])
    @micropost = Micropost.new
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fasttwitter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    "custom", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Londrina+Sketch' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>

<!-- google analytics -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32001653-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

</head>
<body>
	<div class="navbar navbar-fixed-top">
	    <div class="navbar-inner">
	      <div class="container">
	        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </a>
	        <a class="brand" href="/">Fast Twitter</a>
	        <div class="nav-collapse">
	          <ul class="nav">
				<% if current_user %>
				<li><%= link_to "Logout", log_out_path %></li>
				<li><%= link_to current_user.email, user_path(current_user) %>
				<% else %>
				<li><%= link_to "Sign Up", sign_up_path %></li>
				<li><%= link_to "Login", log_in_path %></li>
				<% end %>
				<li><%= link_to "List of Users", users_path %></li>
	          </ul>
	        </div>
	      </div>
	    </div>
	  </div>
	
	<div class="container">
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
	    <div class="row">
	      <div class="span6"><%= yield %></div>
	    </div>
	</div>


</body>
</html>

app/views/microposts/_micropost.html.erb
<%= div_for micropost do %>
	<h3><%= micropost.user.email %></h3>
	<span id="timeago">Posted <%= time_ago_in_words(micropost.created_at) %> ago</span>
	<p id="microcontent">
		<%= micropost.content %>
	</p>
	<% if current_user == @user %>
	<p>
		<%= link_to 'Delete', user_micropost_path(micropost), :method => :delete, :remote => true, :class => 'delete_micropost btn large' %>
	</p>
	<% end %>
	<hr/>
<% end %>

app/views/microposts/create.js.erb
$(document).ready(function() {
	$('.new_micropost').bind('ajax:success', function(event) {
		$('#microposts').prepend('<div class="micropost"><h3>' +  "<%= j @user.email %>" + '</h3><span id="timeago">Posted ' + "<%= j time_ago_in_words(@micropost.created_at) %>" + ' ago</span><p id="microcontent">' +  "<%= j @micropost.content %>" + '</p></div><hr/>');
		$('#new_micropost')[0].reset();
		$('#micropost_count').html('<%= @user.microposts.count %> Microposts');
		$('.new_micropost').unbind('ajax:success');
	});
});

app/views/microposts/destroy.js.erb
$(document).ready(function() {
	$('.delete_micropost').bind('ajax:success', function() {
		$(this).closest('div').slideUp();
		$('#micropost_count').html('<%= @user.microposts.count %> microposts')
	});
});

app/views/pages/about.html.erb
<h1>This is the About Me Page</h1>

app/views/pages/test.html.erb
<div style="float:left;">
	<div id="1sttab">First Tab</div>
	<div id="2ndtab">Second Tab</div>
	<div id="3rdtab">Third Tab</div>
</div>


<%= image_tag('1stimg.png', :id => '1stimg', :class => 'active') %>
<%= image_tag('2ndimg.png', :id => '2ndimg') %>
<%= image_tag('3rdimg.png', :id => '3rdimg') %>

app/views/users/index.html.erb
<h1 id="userlisth1">List of Users</h1>
<div id="#userlist">
<% @users.each do |u| %>
	
	<p><%= link_to u.email, user_path(u) %></p>
	<p><%= u.microposts.count %> Microposts</p>

<% end %>
</div>

app/views/users/new.html.erb
<h1 id="signuph1">Sign Up</h1><br/>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<div id="micropost_container">
<% if logged_in? %>
	<%= form_for [@user, @micropost], :remote => true do |f| %>
		<h1 id="thinking">What are you thinking?</h1><br/>
		<%= f.text_area :content, :class => 'micropostfield' %><br/>
		<%= f.submit :class => 'btn large create_post'%>
		<em>Maximum length is 250 words</em>
	<% end %>
<% else %>
	<h2 id="thinkingwhat"><%= @user.email %>'s Status</h2>
<% end %>

<div id="microposts">
	<%= render @user.microposts.reverse %>
</div>

</div>

<div id="user_info">
	<h2><%= @user.email %></h2>
	<hr />
	<h3 id="micropost_count">		
		<%= @user.microposts.count %> Microposts
	</h3><hr/>
	<h3>
		Joined <%= time_ago_in_words(@user.created_at) %> ago
	</h3>
</div>